import { toYoctoNear } from "./utils/near_formatting_utils";

export const NEAR_DEFAULT_GAS_FOR_FUNCTION_CALL_ACCESS_KEY_HUMAN_NUM = 0.25;
export const NEAR_DEFAULT_GAS_FOR_FUNCTION_CALL_ACCESS_KEY_BIGINT = BigInt(
  toYoctoNear(NEAR_DEFAULT_GAS_FOR_FUNCTION_CALL_ACCESS_KEY_HUMAN_NUM),
);

export const NEAR_MIN_BALANCE_FOR_GAS_REGULAR_HUMAN_NUM = 0.2;
export const NEAR_MIN_BALANCE_FOR_GAS_REGULAR_BIGINT = BigInt(
  toYoctoNear(NEAR_MIN_BALANCE_FOR_GAS_REGULAR_HUMAN_NUM),
);

export const MIN_BALANCE_FOR_CREATE_HUMAN_NUM = 0.1;
export const MIN_BALANCE_FOR_CREATE_BIGINT = BigInt(toYoctoNear(MIN_BALANCE_FOR_CREATE_HUMAN_NUM));

export const NEAR_SYM = "NEAR";
export const NEAR_SYM_ONE_WORD = "Ⓝ";
export const NEAR_DECIMALS = 24;

export const NEAR_PESSIMISTIC_GAS_HUMAN_NUM = 0.2;

// For value smaller than this we would assume it's 0
export const NEAR_SAFE_IGNORE_AMOUNT_YOCTO = "10000000000000";

export const SAFE_NEAR_RESERVE_HUMAN_NUM = 0.2;
export const SAFE_NEAR_RESERVE = "200000000000000000000000"; // 0.2 NEAR
