export enum EOldMeteorErrorId {
  merr_account_access_key_not_found = "merr_account_access_key_not_found",
  merr_sign_message_verify_mismatch = "merr_sign_message_verify_mismatch",
  merr_account_signed_request_mismatch = "merr_account_signed_request_mismatch",
  merr_account_signed_request_not_full_access_key = "merr_account_signed_request_not_full_access_key",
  merr_enrollment_failed = "merr_enrollment_failed",
  merr_enrollment_failed_no_gas = "merr_enrollment_failed_no_gas",
  merr_reward_redeem_failed = "merr_reward_redeem_failed",
  merr_reward_redeem_failed_no_gas = "merr_reward_redeem_failed_no_gas",
  merr_reward_claim_ft_failed = "merr_reward_claim_ft_failed",
  merr_reward_claim_ft_failed_no_gas = "merr_reward_claim_ft_failed_no_gas",
  merr_reward_claim_nft_failed = "merr_reward_claim_nft_failed",
  merr_reward_claim_nft_failed_no_gas = "merr_reward_claim_nft_failed_no_gas",
  merr_unwrap_near_failed = "merr_unwrap_near_failed",
  merr_profile_update_failed = "merr_profile_update_failed",
  merr_profile_update_pfp_failed = "merr_profile_update_pfp_failed",
}
