export enum ENearIndexer_AccessKeyPermission {
  FULL_ACCESS = "FULL_ACCESS",
  FUNCTION_CALL = "FUNCTION_CALL",
}

export enum ENearIndexer_ActionType {
  TRANSFER = "TRANSFER",
  FUNCTION_CALL = "FUNCTION_CALL",
  DELETE_KEY = "DELETE_KEY",
  DEPLOY_CONTRACT = "DEPLOY_CONTRACT",
  CREATE_ACCOUNT = "CREATE_ACCOUNT",
  DELETE_ACCOUNT = "DELETE_ACCOUNT",
}
